BOARD_TAG    = uno
USER_LIB_PATH = $(realpath ../Libraries)
CPPFLAGS += -DMY_ADDRESS=${ADDRESS}
# MONITOR_PORT = /dev/cu.usbmodem141
# MONITOR_PORT = /dev/cu.usbmodem14221
# MONITOR_PORT = /dev/cu.usbmodem14211
include /usr/local/opt/arduino-mk/Arduino.mk